In [6]:
# COM424 Lab Exercise
# 1.Introduction to Numpy

# COM424 Lab Exercise
# 1.Introduction to Numpy

In [7]:
import numpy as np

In [8]:
print("Numpy version :", np._version_)

AttributeError: module 'numpy' has no attribute '_version_'

In [12]:
a = list()
print(" Variable a has type ")
print(type(a))
a = 2
print(" Variable a has type ")
print(type(a))


 Variable a has type 
<class 'list'>
 Variable a has type 
<class 'int'>


In [15]:
a = np.array([1, 2, 3, 4, 5])

In [17]:
type(a)
print(" Data type of numpy array a is ", a.dtype)

 Data type of numpy array a is  int64


In [18]:
b = [1, 'a', 3.0, type(a)]
print(b)

[1, 'a', 3.0, <class 'numpy.ndarray'>]


In [19]:
c = np.array(b)
print("Contents of numpy c are", c)

Contents of numpy c are [1 'a' 3.0 <class 'numpy.ndarray'>]


In [20]:
print("Data type of numpy array c is", c.dtype)

Data type of numpy array c is object


In [22]:
d = np.array([1,2,3.0,4,6,7], dtype='float')
d

array([1., 2., 3., 4., 6., 7.])

In [23]:
e = np.random.randn(3)
e

array([-1.31278472, -0.80000437,  1.25599888])

In [24]:
#evenly spaced
f = np.linspace(0,10,5)
f

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

An array with an incremental range of numbers


In [25]:
z = np.arange(0,100)# simirar to python's range
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
#utility functions
z.ndim
#z.shape(specifies how many elements in total) 
print("Z's size is",z.size)

1

# Create multidimansional array from the array `z`

In [32]:
z_2d = z.reshape(25,4)
print(z_2d.shape)
z_2d

(25, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [33]:
z == z.reshape(100,1) # check the quality

array([[ True, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False, False, ...,  True, False, False],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False,  True]])

# Create a `25 x 4` multidimensional array from the array z_2d

In [34]:
z_25x4 = z_2d.reshape(4,25)
z_25x4.shape


(4, 25)

# we let numpy to calculate the number of column by giving it -1, since we only know the number of row which is 4 depending on the number of elements in the array.

In [36]:
z_reshaped = z_2d.reshape(4, -1) 
z_25x4.shape


(4, 25)

In [35]:
z_trans = z_2d.T
z_trans.shape


(4, 25)

# make z array to be 3 dimensional array

In [37]:
z_10x5x2 = z.reshape(10,5,2)
z_10x5x2.shape

(10, 5, 2)

In [38]:
z_10x5x2.ndim

3

# array indexing and slicing

In [39]:
z[76]

76

In [40]:
z_2d[19,0]

76

In [41]:
z_76_index_mask = np.where(z_2d == 76)
z_76_index_mask

(array([19]), array([0]))

In [43]:
z_2d[z_76_index_mask]

array([76])

In [44]:
z_2d[3,:] # get all elements in raw number 3 all the way where it has ended

array([12, 13, 14, 15])

In [45]:
z_2d[3,0:2] # elements in raw 4 

array([12, 13])

In [47]:
z_2d[3,0::2]

array([12, 14])